name: Gerar Executável (Build)

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'

    - name: Instalar Dependências de Interface e som do Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libportaudio2

    - name: Instalar Dependências do Projeto
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter psutil py_cpuinfo pyinstaller sounddevice miniaudio numpy

    - name: Instalar WMI para Windows
      if: matrix.os == 'windows-latest'
      run: pip install wmi

    - name: Compilar para Windows com PyInstaller
      if: matrix.os == 'windows-latest'
      run: |
        $ctk_path = python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))"
        pyinstaller --windowed --onedir --hidden-import=pywintypes --name "cpu-py-windows" --add-data="${ctk_path};customtkinter/" --add-data="src/Corinthians vinheta da Radio! Corinthians.mp3;src/" main.py

    - name: Compilar para Linux com PyInstaller
      if: matrix.os == 'ubuntu-latest'
      run: |
        ctk_path=$(python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))")
        pyinstaller --windowed --onedir --name "cpu-py-linux" --add-data="${ctk_path}:customtkinter/" --add-data="src/Corinthians vinheta da Radio! Corinthians.mp3:src/" main.py

    - name: Compactar o Executável (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        Compress-Archive -Path "cpu-py-windows" -DestinationPath "../cpu-py-windows.zip"

    - name: Compactar o Executável (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dist
        zip -r ../cpu-py-linux.zip cpu-py-linux

    - name: Salvar artefato Provisório
      uses: actions/upload-artifact@v4
      with:
        name: executavel-${{ matrix.os }}
        path: cpu-py-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Baixar todos os artefatos gerados
        uses: actions/download-artifact@v4
        with:
          pattern: executavel-*
          merge-multiple: true

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          files: cpu-py-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
