name: Gerar Executável (Build)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'

    - name: Instalar Dependências de Interface e som do Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk libportaudio2

    - name: Instalar Dependências do Projeto
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter psutil py_cpuinfo pyinstaller sounddevice miniaudio numpy

    - name: Instalar WMI para Windows
      if: matrix.os == 'windows-latest'
      run: pip install wmi

    - name: Compilar para Windows com PyInstaller
      if: matrix.os == 'windows-latest'
      run: |
        $ctk_path = python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))"
        pyinstaller --windowed --onedir --hidden-import=pywintypes --name "cpu-py-windows" --add-data="${ctk_path};customtkinter/" --add-data="src/Corinthians vinheta da Radio! Corinthians.mp3;src/" main.py

    - name: Compilar para Linux com PyInstaller
      if: matrix.os == 'ubuntu-latest'
      run: |
        ctk_path = $(python -c "import customtkinter, os; print(os.path.dirname(customtkinter.__file__))")
        pyinstaller --windowed --onedir --name "cpu-py-linux" --add-data="${ctk_path}:customtkinter/" --add-data="src/Corinthians vinheta da Radio! Corinthians.mp3:src/" main.py

    - name: Disponibilizar os Executáveis para Download
      uses: actions/upload-artifact@v4
      with:
        name: cpu-py-${{ matrix.os }}
        path: dist/
